import { db } from "@/lib/db/client";
import { users } from "@/lib/db/schema.runtime";
import bcrypt from "bcryptjs";

async function seed() {
  const passwordHash = await bcrypt.hash("password123", 10);

  // ADMIN - Initial System Setup
  await db.insert(users).values({
    name: "System Administrator",
    email: "admin@campus.edu",
    passwordHash,
    role: "ADMIN",
    departmentId: "CSE",
    isHosteller: false,
    createdAt: "2025-01-05T08:14:22Z",
  });

  // HODs - Department Onboarding
  await db.insert(users).values([
    { name: "Dr. Anil Kumar", email: "hod.cse@campus.edu", passwordHash, role: "HOD", departmentId: "CSE", createdAt: "2025-05-10T09:12:05Z" },
    { name: "Dr. Meera Iyer", email: "hod.it@campus.edu", passwordHash, role: "HOD", departmentId: "IT", createdAt: "2025-05-10T11:45:30Z" },
    { name: "Dr. Raghav Rao", email: "hod.ece@campus.edu", passwordHash, role: "HOD", departmentId: "ECE", createdAt: "2025-05-11T10:20:14Z" },
    { name: "Dr. Sneha Menon", email: "hod.eee@campus.edu", passwordHash, role: "HOD", departmentId: "EEE", createdAt: "2025-05-11T14:05:45Z" },
    { name: "Dr. Arvind Patel", email: "hod.mech@campus.edu", passwordHash, role: "HOD", departmentId: "MECH", createdAt: "2025-05-12T09:33:12Z" },
    { name: "Dr. Kavita Sharma", email: "hod.civil@campus.edu", passwordHash, role: "HOD", departmentId: "CIVIL", createdAt: "2025-05-12T16:12:55Z" },
  ]);

  // 30 CSE Students - Registration: Early July
  await db.insert(users).values([
    { name: "Aarav Mishra", email: "cse1@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: true, createdAt: "2025-07-01T10:05:12Z" },
    { name: "Riya Sen", email: "cse2@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: false, createdAt: "2025-07-01T10:12:45Z" },
    { name: "Kunal Verma", email: "cse3@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: true, createdAt: "2025-07-01T10:25:03Z" },
    { name: "Tanvi Kapoor", email: "cse4@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: false, createdAt: "2025-07-01T10:44:19Z" },
    { name: "Dev Malhotra", email: "cse5@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: false, createdAt: "2025-07-01T11:02:33Z" },
    { name: "Ishaan Roy", email: "cse6@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: true, createdAt: "2025-07-01T11:15:54Z" },
    { name: "Maya Jain", email: "cse7@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: false, createdAt: "2025-07-01T11:38:21Z" },
    { name: "Nikhil Das", email: "cse8@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: true, createdAt: "2025-07-01T11:55:08Z" },
    { name: "Pooja Reddy", email: "cse9@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: false, createdAt: "2025-07-01T12:10:47Z" },
    { name: "Arjun Nair", email: "cse10@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: false, createdAt: "2025-07-01T12:25:12Z" },
    { name: "Simran Gill", email: "cse11@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: true, createdAt: "2025-07-02T09:04:33Z" },
    { name: "Rohit Sinha", email: "cse12@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: false, createdAt: "2025-07-02T09:18:02Z" },
    { name: "Megha Dutta", email: "cse13@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: false, createdAt: "2025-07-02T09:42:55Z" },
    { name: "Aditya Singh", email: "cse14@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: true, createdAt: "2025-07-02T10:02:11Z" },
    { name: "Neha Agarwal", email: "cse15@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: false, createdAt: "2025-07-02T10:15:36Z" },
    { name: "Varun Chopra", email: "cse16@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: false, createdAt: "2025-07-02T10:35:01Z" },
    { name: "Ira Bansal", email: "cse17@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: true, createdAt: "2025-07-02T11:01:29Z" },
    { name: "Sahil Khanna", email: "cse18@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: false, createdAt: "2025-07-02T11:15:58Z" },
    { name: "Ananya Paul", email: "cse19@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: true, createdAt: "2025-07-02T11:30:14Z" },
    { name: "Harsh Vyas", email: "cse20@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: false, createdAt: "2025-07-02T11:55:40Z" },
    { name: "Ritika Bose", email: "cse21@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: false, createdAt: "2025-07-03T10:10:12Z" },
    { name: "Yash Tiwari", email: "cse22@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: true, createdAt: "2025-07-03T10:25:59Z" },
    { name: "Priya Narang", email: "cse23@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: false, createdAt: "2025-07-03T10:40:02Z" },
    { name: "Deepak Pillai", email: "cse24@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: true, createdAt: "2025-07-03T11:01:31Z" },
    { name: "Zoya Khan", email: "cse25@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: false, createdAt: "2025-07-03T11:15:19Z" },
    { name: "Rahul Bhat", email: "cse26@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: false, createdAt: "2025-07-03T11:30:44Z" },
    { name: "Tanya Sethi", email: "cse27@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: true, createdAt: "2025-07-03T11:55:05Z" },
    { name: "Karthik Iyer", email: "cse28@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: false, createdAt: "2025-07-03T12:10:22Z" },
    { name: "Aditi Kulkarni", email: "cse29@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: true, createdAt: "2025-07-03T12:25:50Z" },
    { name: "Naman Gupta", email: "cse30@campus.edu", passwordHash, role: "STUDENT", departmentId: "CSE", isHosteller: false, createdAt: "2025-07-03T12:50:11Z" },
  ]);

  // 30 IT Students - Registration: Mid July
  await db.insert(users).values([
    { name: "Aman Verma", email: "it1@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: true, createdAt: "2025-07-10T09:05:22Z" },
    { name: "Shruti Nanda", email: "it2@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: false, createdAt: "2025-07-10T09:15:55Z" },
    { name: "Rohan Kulshreshtha", email: "it3@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: true, createdAt: "2025-07-10T09:30:11Z" },
    { name: "Diya Thomas", email: "it4@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: false, createdAt: "2025-07-10T09:45:04Z" },
    { name: "Keshav Arora", email: "it5@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: false, createdAt: "2025-07-10T10:01:36Z" },
    { name: "Lavanya Pillai", email: "it6@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: true, createdAt: "2025-07-10T10:15:19Z" },
    { name: "Manav Kohli", email: "it7@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: false, createdAt: "2025-07-10T10:30:52Z" },
    { name: "Reet Kaur", email: "it8@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: true, createdAt: "2025-07-10T10:45:11Z" },
    { name: "Yuvraj Bedi", email: "it9@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: false, createdAt: "2025-07-10T11:01:44Z" },
    { name: "Isha Venkatesh", email: "it10@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: false, createdAt: "2025-07-10T11:15:27Z" },
    { name: "Arnav Joshi", email: "it11@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: true, createdAt: "2025-07-11T09:30:59Z" },
    { name: "Snehal Patil", email: "it12@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: false, createdAt: "2025-07-11T09:45:12Z" },
    { name: "Tushar Rathi", email: "it13@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: false, createdAt: "2025-07-11T10:01:41Z" },
    { name: "Nikita Rao", email: "it14@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: true, createdAt: "2025-07-11T10:15:23Z" },
    { name: "Gaurav Mahajan", email: "it15@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: false, createdAt: "2025-07-11T10:30:51Z" },
    { name: "Ankita Pradhan", email: "it16@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: false, createdAt: "2025-07-11T10:45:09Z" },
    { name: "Devika Sharma", email: "it17@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: true, createdAt: "2025-07-11T11:01:34Z" },
    { name: "Ritvik Anand", email: "it18@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: false, createdAt: "2025-07-11T11:15:16Z" },
    { name: "Pallavi Jain", email: "it19@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: true, createdAt: "2025-07-11T11:30:58Z" },
    { name: "Omkar Deshpande", email: "it20@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: false, createdAt: "2025-07-11T11:45:10Z" },
    { name: "Rachit Malhotra", email: "it21@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: false, createdAt: "2025-07-12T09:01:47Z" },
    { name: "Sanya Khurana", email: "it22@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: true, createdAt: "2025-07-12T09:16:15Z" },
    { name: "Parth Mehta", email: "it23@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: false, createdAt: "2025-07-12T09:31:52Z" },
    { name: "Vaani Chopra", email: "it24@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: true, createdAt: "2025-07-12T09:46:11Z" },
    { name: "Rudra Banerjee", email: "it25@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: false, createdAt: "2025-07-12T10:02:44Z" },
    { name: "Shivam Dubey", email: "it26@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: false, createdAt: "2025-07-12T10:17:19Z" },
    { name: "Mitali Saha", email: "it27@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: true, createdAt: "2025-07-12T10:32:51Z" },
    { name: "Karan Batra", email: "it28@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: false, createdAt: "2025-07-12T10:47:11Z" },
    { name: "Ayesha Siddiqui", email: "it29@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: true, createdAt: "2025-07-12T11:03:45Z" },
    { name: "Harshit Garg", email: "it30@campus.edu", passwordHash, role: "STUDENT", departmentId: "IT", isHosteller: false, createdAt: "2025-07-12T11:18:22Z" },
  ]);

  // 30 ECE Students - Registration: Late July
  await db.insert(users).values([
    { name: "Advik Rao", email: "ece1@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: true, createdAt: "2025-07-20T09:10:33Z" },
    { name: "Shreya Iyer", email: "ece2@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: false, createdAt: "2025-07-20T09:25:01Z" },
    { name: "Pranav Kulkarni", email: "ece3@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: true, createdAt: "2025-07-20T09:40:44Z" },
    { name: "Ritika Menon", email: "ece4@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: false, createdAt: "2025-07-20T09:55:12Z" },
    { name: "Dhruv Soni", email: "ece5@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: false, createdAt: "2025-07-20T10:10:39Z" },
    { name: "Anjali Nair", email: "ece6@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: true, createdAt: "2025-07-20T10:25:11Z" },
    { name: "Siddharth Jain", email: "ece7@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: false, createdAt: "2025-07-20T10:40:55Z" },
    { name: "Nehal Kapoor", email: "ece8@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: true, createdAt: "2025-07-20T10:55:22Z" },
    { name: "Yamini Pillai", email: "ece9@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: false, createdAt: "2025-07-20T11:10:47Z" },
    { name: "Vivek Narayan", email: "ece10@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: false, createdAt: "2025-07-20T11:25:01Z" },
    { name: "Kritika Sen", email: "ece11@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: true, createdAt: "2025-07-21T09:40:33Z" },
    { name: "Harini Balan", email: "ece12@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: false, createdAt: "2025-07-21T09:55:54Z" },
    { name: "Rajat Malviya", email: "ece13@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: false, createdAt: "2025-07-21T10:10:19Z" },
    { name: "Tejaswini Rao", email: "ece14@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: true, createdAt: "2025-07-21T10:25:40Z" },
    { name: "Amanpreet Singh", email: "ece15@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: false, createdAt: "2025-07-21T10:40:02Z" },
    { name: "Lakshmi V", email: "ece16@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: false, createdAt: "2025-07-21T10:55:29Z" },
    { name: "Naveen R", email: "ece17@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: true, createdAt: "2025-07-21T11:10:51Z" },
    { name: "Priyanshu Rawat", email: "ece18@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: false, createdAt: "2025-07-21T11:25:14Z" },
    { name: "Charvi Gupta", email: "ece19@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: true, createdAt: "2025-07-21T11:40:38Z" },
    { name: "Ashwin Bhat", email: "ece20@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: false, createdAt: "2025-07-21T11:55:01Z" },
    { name: "Mrunal Desai", email: "ece21@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: false, createdAt: "2025-07-22T09:10:46Z" },
    { name: "Rhea Thomas", email: "ece22@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: true, createdAt: "2025-07-22T09:25:19Z" },
    { name: "Akshay Patankar", email: "ece23@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: false, createdAt: "2025-07-22T09:40:42Z" },
    { name: "Ishika Sharma", email: "ece24@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: true, createdAt: "2025-07-22T09:55:05Z" },
    { name: "Tarun Bansal", email: "ece25@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: false, createdAt: "2025-07-22T10:10:33Z" },
    { name: "Shravan Iyer", email: "ece26@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: false, createdAt: "2025-07-22T10:25:54Z" },
    { name: "Diya Kapoor", email: "ece27@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: true, createdAt: "2025-07-22T10:40:11Z" },
    { name: "Samarjit Bose", email: "ece28@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: false, createdAt: "2025-07-22T10:55:40Z" },
    { name: "Neeraj Tripathi", email: "ece29@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: true, createdAt: "2025-07-22T11:10:22Z" },
    { name: "Avni Srivastava", email: "ece30@campus.edu", passwordHash, role: "STUDENT", departmentId: "ECE", isHosteller: false, createdAt: "2025-07-22T11:25:51Z" },
  ]);

  // 30 EEE Students - Registration: Early August
  await db.insert(users).values([
    { name: "Rohit Choudhary", email: "eee1@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: true, createdAt: "2025-08-01T08:05:41Z" },
    { name: "Ananya Mishra", email: "eee2@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: false, createdAt: "2025-08-01T08:15:02Z" },
    { name: "Samar Verma", email: "eee3@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: true, createdAt: "2025-08-01T08:30:33Z" },
    { name: "Priya Bansal", email: "eee4@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: false, createdAt: "2025-08-01T08:45:55Z" },
    { name: "Aditya Prakash", email: "eee5@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: false, createdAt: "2025-08-01T09:02:11Z" },
    { name: "Naina Grover", email: "eee6@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: true, createdAt: "2025-08-01T09:18:44Z" },
    { name: "Tanishq Arora", email: "eee7@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: false, createdAt: "2025-08-01T09:35:01Z" },
    { name: "Pooja Nambiar", email: "eee8@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: true, createdAt: "2025-08-01T09:50:39Z" },
    { name: "Manish Patra", email: "eee9@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: false, createdAt: "2025-08-01T10:05:22Z" },
    { name: "Kavya Pillai", email: "eee10@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: false, createdAt: "2025-08-01T10:22:55Z" },
    { name: "Yogesh Yadav", email: "eee11@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: true, createdAt: "2025-08-02T10:40:11Z" },
    { name: "Ritika Soni", email: "eee12@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: false, createdAt: "2025-08-02T10:55:44Z" },
    { name: "Saket Jain", email: "eee13@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: false, createdAt: "2025-08-02T11:10:01Z" },
    { name: "Vaishali Deshmukh", email: "eee14@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: true, createdAt: "2025-08-02T11:25:39Z" },
    { name: "Anirudh Rao", email: "eee15@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: false, createdAt: "2025-08-02T11:45:22Z" },
    { name: "Megha Thomas", email: "eee16@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: false, createdAt: "2025-08-02T12:05:55Z" },
    { name: "Raghav Batra", email: "eee17@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: true, createdAt: "2025-08-02T12:20:11Z" },
    { name: "Sanya Iyer", email: "eee18@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: false, createdAt: "2025-08-02T12:40:44Z" },
    { name: "Nikhil Mohan", email: "eee19@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: true, createdAt: "2025-08-02T13:05:01Z" },
    { name: "Prarthana Roy", email: "eee20@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: false, createdAt: "2025-08-02T13:25:39Z" },
    { name: "Harsh Vardhan", email: "eee21@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: false, createdAt: "2025-08-03T13:45:22Z" },
    { name: "Aditi Kulkarni", email: "eee22@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: true, createdAt: "2025-08-03T14:05:55Z" },
    { name: "Ramesh Naik", email: "eee23@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: false, createdAt: "2025-08-03T14:25:11Z" },
    { name: "Ira Chatterjee", email: "eee24@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: true, createdAt: "2025-08-03T14:45:44Z" },
    { name: "Kunal Sharma", email: "eee25@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: false, createdAt: "2025-08-03T15:05:01Z" },
    { name: "Divyanshi Mehta", email: "eee26@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: false, createdAt: "2025-08-03T15:25:39Z" },
    { name: "Aman Gupta", email: "eee27@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: true, createdAt: "2025-08-03T15:45:22Z" },
    { name: "Shreya Dutta", email: "eee28@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: false, createdAt: "2025-08-03T16:05:55Z" },
    { name: "Parag Shetty", email: "eee29@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: true, createdAt: "2025-08-03T16:25:11Z" },
    { name: "Mansi Kapoor", email: "eee30@campus.edu", passwordHash, role: "STUDENT", departmentId: "EEE", isHosteller: false, createdAt: "2025-08-03T16:45:44Z" },
  ]);

  // 30 MECH Students - Registration: Mid August
  await db.insert(users).values([
    { name: "Arjun Singh", email: "mech1@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: true, createdAt: "2025-08-10T10:05:41Z" },
    { name: "Kriti Yadav", email: "mech2@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: false, createdAt: "2025-08-10T10:15:02Z" },
    { name: "Dev Malhotra", email: "mech3@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: true, createdAt: "2025-08-10T10:30:33Z" },
    { name: "Sneha Kulkarni", email: "mech4@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: false, createdAt: "2025-08-10T10:45:55Z" },
    { name: "Rajat Chauhan", email: "mech5@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: false, createdAt: "2025-08-10T11:02:11Z" },
    { name: "Aarohi Mehra", email: "mech6@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: true, createdAt: "2025-08-10T11:15:44Z" },
    { name: "Manav Reddy", email: "mech7@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: false, createdAt: "2025-08-10T11:35:01Z" },
    { name: "Pallavi S", email: "mech8@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: true, createdAt: "2025-08-10T11:55:39Z" },
    { name: "Lakshay Jain", email: "mech9@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: false, createdAt: "2025-08-10T12:10:22Z" },
    { name: "Ishaan Bhat", email: "mech10@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: false, createdAt: "2025-08-10T12:25:55Z" },
    { name: "Anvi Patel", email: "mech11@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: true, createdAt: "2025-08-11T12:40:11Z" },
    { name: "Vikram Raj", email: "mech12@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: false, createdAt: "2025-08-11T12:55:44Z" },
    { name: "Tanya Goyal", email: "mech13@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: false, createdAt: "2025-08-11T13:10:01Z" },
    { name: "Rohini Das", email: "mech14@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: true, createdAt: "2025-08-11T13:25:39Z" },
    { name: "Om Tiwari", email: "mech15@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: false, createdAt: "2025-08-11T13:40:22Z" },
    { name: "Simran Gill", email: "mech16@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: false, createdAt: "2025-08-11T13:55:55Z" },
    { name: "Harshit Rao", email: "mech17@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: true, createdAt: "2025-08-11T14:10:11Z" },
    { name: "Nisha Menon", email: "mech18@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: false, createdAt: "2025-08-11T14:25:44Z" },
    { name: "Rishi Pandey", email: "mech19@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: true, createdAt: "2025-08-11T14:40:01Z" },
    { name: "Aishwarya K", email: "mech20@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: false, createdAt: "2025-08-11T14:55:39Z" },
    { name: "Gaurang Dave", email: "mech21@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: false, createdAt: "2025-08-12T15:10:22Z" },
    { name: "Nidhi Kapoor", email: "mech22@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: true, createdAt: "2025-08-12T15:25:55Z" },
    { name: "Pranav Sahu", email: "mech23@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: false, createdAt: "2025-08-12T15:40:11Z" },
    { name: "Mitali Roy", email: "mech24@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: true, createdAt: "2025-08-12T15:55:44Z" },
    { name: "Yash Bansal", email: "mech25@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: false, createdAt: "2025-08-12T16:10:01Z" },
    { name: "Deepa Saini", email: "mech26@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: false, createdAt: "2025-08-12T16:25:39Z" },
    { name: "Raghunath N", email: "mech27@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: true, createdAt: "2025-08-12T16:40:22Z" },
    { name: "Siddhi Kulkarni", email: "mech28@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: false, createdAt: "2025-08-12T16:55:55Z" },
    { name: "Arpita Singh", email: "mech29@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: true, createdAt: "2025-08-12T17:10:11Z" },
    { name: "Rahul Nair", email: "mech30@campus.edu", passwordHash, role: "STUDENT", departmentId: "MECH", isHosteller: false, createdAt: "2025-08-12T17:25:44Z" },
  ]);

  // 30 CIVIL Students - Registration: Late August
  await db.insert(users).values([
    { name: "Adarsh P", email: "civil1@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: true, createdAt: "2025-08-20T09:05:41Z" },
    { name: "Shalini Rao", email: "civil2@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: false, createdAt: "2025-08-20T09:15:02Z" },
    { name: "Karthik R", email: "civil3@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: true, createdAt: "2025-08-20T09:30:33Z" },
    { name: "Rhea Jain", email: "civil4@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: false, createdAt: "2025-08-20T09:45:55Z" },
    { name: "Naman Goyal", email: "civil5@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: false, createdAt: "2025-08-20T10:02:11Z" },
    { name: "Ishita Bose", email: "civil6@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: true, createdAt: "2025-08-20T10:15:44Z" },
    { name: "Yuvika Sharma", email: "civil7@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: false, createdAt: "2025-08-20T10:35:01Z" },
    { name: "Rohan Iyer", email: "civil8@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: true, createdAt: "2025-08-20T10:55:39Z" },
    { name: "Tanya Singh", email: "civil9@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: false, createdAt: "2025-08-20T11:10:22Z" },
    { name: "Dhruvi Patel", email: "civil10@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: false, createdAt: "2025-08-20T11:25:55Z" },
    { name: "Aarav B", email: "civil11@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: true, createdAt: "2025-08-21T11:40:11Z" },
    { name: "Sana Ali", email: "civil12@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: false, createdAt: "2025-08-21T11:55:44Z" },
    { name: "Prithvi Raj", email: "civil13@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: false, createdAt: "2025-08-21T12:10:01Z" },
    { name: "Mahi Verma", email: "civil14@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: true, createdAt: "2025-08-21T12:25:39Z" },
    { name: "Nikhita S", email: "civil15@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: false, createdAt: "2025-08-21T12:40:22Z" },
    { name: "Saurabh Meena", email: "civil16@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: false, createdAt: "2025-08-21T12:55:55Z" },
    { name: "Varun Kaul", email: "civil17@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: true, createdAt: "2025-08-21T13:10:11Z" },
    { name: "Neeti Kaur", email: "civil18@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: false, createdAt: "2025-08-21T13:25:44Z" },
    { name: "Jatin Malviya", email: "civil19@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: true, createdAt: "2025-08-21T13:40:01Z" },
    { name: "Akriti Das", email: "civil20@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: false, createdAt: "2025-08-21T13:55:39Z" },
    { name: "Rachna G", email: "civil21@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: false, createdAt: "2025-08-22T14:10:22Z" },
    { name: "Tejas P", email: "civil22@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: true, createdAt: "2025-08-22T14:25:55Z" },
    { name: "Suhani Bhatia", email: "civil23@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: false, createdAt: "2025-08-22T14:40:11Z" },
    { name: "Yashika R", email: "civil24@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: true, createdAt: "2025-08-22T14:55:44Z" },
    { name: "Madhav L", email: "civil25@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: false, createdAt: "2025-08-22T15:10:01Z" },
    { name: "Harleen S", email: "civil26@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: false, createdAt: "2025-08-22T15:25:39Z" },
    { name: "Ritik Anand", email: "civil27@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: true, createdAt: "2025-08-22T15:40:22Z" },
    { name: "Apeksha N", email: "civil28@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: false, createdAt: "2025-08-22T15:55:55Z" },
    { name: "Nilesh S", email: "civil29@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: true, createdAt: "2025-08-22T16:10:11Z" },
    { name: "Diksha M", email: "civil30@campus.edu", passwordHash, role: "STUDENT", departmentId: "CIVIL", isHosteller: false, createdAt: "2025-08-22T16:25:44Z" },
  ]);

  console.log("Users seeded successfully with unique 2025 text-formatted timestamps.");
}

seed();